<?php

/**
 *  @file
 *  The install file for the abcslideshow module.
 */


/**
 * Implements hook_install().
 */
  function abcslideshow_install() {
    //
  }


/** Implements hook_uninstall().
 *
 */

  function abcslideshow_uninstall() {

    // Delete variables
      variable_del('abcslideshow_active');
      variable_del('abcslideshow_images_list');
      variable_del('abcslideshow_js_script');
  }


